---
title: "Untitled"
output: html_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(dplyr)
library(AER)
library(lspline)
library(fixest)
library(modelsummary)
library(ggpubr)
library(reshape2)
library(kableExtra)
library(ggplot2)
library(tidyverse)
library(haven)
library(data.table)
library(huxtable)
library(pscl)
library(patchwork)
library(MASS)
```


```{r}
## read data set
df <- read_csv("healthcare-dataset-stroke-data.csv")
df <- df %>% drop_na()

# removing one "Other" in the gender column
df <- filter(df, df$gender != "Other")
```


```{r}
#filter age group 18 or above, delete 5 rows which work_type == "never_worked"
df <- df %>% filter(age > 17) %>%  
  filter(work_type != "Never_worked")

# transform column vlaues and binary values
df$gender[df$gender == "Female"] <- 0
df$gender[df$gender == "Male"] <- 1

df$ever_married[df$ever_married == "Yes"] <- 1
df$ever_married[df$ever_married == "No"] <- 0

df$Residence_type[df$Residence_type == "Urban"] <- 1
df$Residence_type[df$Residence_type == "Rural"] <- 0

df$smoking_status[df$smoking_status == "smokes"] <- 1
df$smoking_status[df$smoking_status == "formerly smoked"] <- 0
df$smoking_status[df$smoking_status == "Unknown"] <- 0
df$smoking_status[df$smoking_status == "never smoked"] <- 0

df$work_type[df$work_type == "Private"] <- 1
df$work_type[df$work_type == "Self-employed"] <- 1
df$work_type[df$work_type == "Govt_job"] <- 0

# transform the whole table to numeric
df$gender <- as.numeric(df$gender)
df$ever_married <- as.numeric(df$ever_married)
df$work_type <- as.numeric(df$work_type)
df$Residence_type <- as.numeric(df$Residence_type)
df$smoking_status <- as.numeric(df$smoking_status)
df$bmi <- as.numeric(df$bmi)

```


```{r}

P95 <- function(x){quantile(x,0.95,na.rm=T)}
P05 <- function(x){quantile(x,0.05,na.rm=T)}
datasummary( (`Stroke` = stroke ) + 
               (`Male` = gender) +
               (`Married` = ever_married) +
               (`Age` = age) +
               (`Heart Disease` = heart_disease) +
               (`Private Work` = work_type) +
               (`Living in Urban` = Residence_type) +
               (`Smoker` = smoking_status) + 
               (`BMI` = bmi) +
               (`Glucose Level` = avg_glucose_level) ~
             Mean + Median + SD + Min + Max + P05 + P95 , 
             data = df ,
             title = 'Descriptive statistics') %>% 
      kable_styling(latex_options = c("HOLD_position","scale_down"))


```

```{r message=FALSE, warning=FALSE}
# Correlation matrix
cT <- round( cor( df , use = "complete.obs") , 2 )
# create a lower triangular matrix
cT[ upper.tri( cT ) ] <- NA
# Put it into a tibble format
melted_cormat <- melt( cT , na.rm = TRUE)
# Now we can create a heat-map
ggplot( data = melted_cormat, aes( Var2 , Var1 , fill = value ) )+
  geom_tile( color = "white" ) +
  scale_fill_gradient2(low = "navyblue", high = "darkgreen", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Correlation") +
  theme_bw()+ 
  theme( axis.text.x = element_text(angle = 45, vjust = 1, 
                                    size = 10, hjust = 1))+
  labs(y="",x="")+
  coord_fixed() +
  ggtitle("Correlation Matrix")


```

```{r message=FALSE, warning=FALSE}
# Prob of men getting stroke
lpmmen <- feols( stroke ~ gender , data = df , vcov = 'hetero' )
df$predmen <- predict( lpmmen )

gw <- ggplot(data = df) +
  geom_point(aes(x = gender, y = predmen), size = 1, shape = 16) +
  geom_line(aes(x = gender, y = predmen),  size=0.7) +
  labs(x = "Gender",y = "Predicted probability of having stroke")+
  coord_cartesian(xlim = c(0, 1), ylim=c(0,0.1)) +
  theme_light() + 
  ggtitle("Figure 1 : Men's Probablility of getting stroke")
gw
```

```{r message=FALSE, warning=FALSE}
# Prob of married person getting stroke
lpmmar <- feols( stroke ~ ever_married , data = df , vcov = 'hetero' )
df$predmar <- predict( lpmmar )

gmar <- ggplot(data = df) +
  geom_point(aes(x = ever_married, y = predmar), size = 1, shape = 16) +
  geom_line(aes(x = ever_married, y = predmar),  size=0.7) +
  labs(x = "Marriage",y = "Predicted probability of having stroke")+
  coord_cartesian(xlim = c(0, 1), ylim=c(0,0.1)) +
  theme_light() + 
  ggtitle("Figure 2 : Married person Probablility of getting stroke")
gmar
```

```{r message=FALSE, warning=FALSE}
# Model 0, estimation table of stroke, by gender and marriage
summary0 <- etable( lpmmen , lpmmar ,
        se.below = T,
        coefstat = 'se',
        fitstat = c('n','r2'), 
        dict=c("gender" = "Men", "ever_married" = "Married"))
summary0
```

```{r message=FALSE, warning=FALSE}
lpm0 <- lm(stroke ~ gender, data=df)
logit0 <- glm(stroke ~ gender, data=df, family = binomial ( link = "logit"))
probit0 <- glm(stroke ~ gender, data=df, family=binomial(link="probit"))
```

```{r message=FALSE, warning=FALSE}
model_formula1 <- formula(stroke ~ gender + ever_married)
lpm1 <-lm(model_formula1, data=df, vcov = "hetreo")
logit1 <- glm(model_formula1, data=df, family = binomial ( link = "logit"))
probit1 <- glm(model_formula1, data=df, family=binomial(link="probit"))
```

```{r message=FALSE, warning=FALSE}
model_formula2 <- formula(stroke ~ gender + ever_married + age)
lpm2 <-lm(model_formula2, data=df, vcov = "hetreo")
logit2 <- glm(model_formula2, data=df, family = binomial ( link = "logit"))
probit2 <- glm(model_formula2, data=df, family=binomial(link="probit"))
```

```{r message=FALSE, warning=FALSE}

# Model 3
model_formula3 <- formula(stroke ~ gender + ever_married + age + avg_glucose_level + smoking_status)

lpm3 <-lm(model_formula3, data=df, vcov = "hetreo")
df$pred_lpm3 <- predict(lpm3)


# Logit coefficients

logit3 <- glm(model_formula3, data=df, family = binomial ( link = "logit"))

# Predicted probabilities 
df$pred_logit3 <- predict.glm(logit3, type="response")


# Logit marginal differences
library(mfx)
logit_marg3 <- logitmfx(model_formula3, data=df, atmean=FALSE, robust = T)

```

```{r message=FALSE, warning=FALSE}
# Probit coefficients
probit3 <- glm(model_formula3, data=df, family=binomial(link="probit"))

# Predicted probabilities 
df$pred_probit3<- predict.glm(probit3, type="response") 

# Probit marginal differences
probit_marg3 <- probitmfx(model_formula3, data=df, atmean=FALSE, robust = T)
```

```{r message=FALSE, warning=FALSE}
glance_custom.glm <- function(x) data.frame(`PseudoR2` = pR2(x)["McFadden"])
cm <- c('(Intercept)' = 'Constant')

summary1 <- msummary(list("(M0) logit" = logit0, "(M0) Probit" = probit0, "(M1) logit" = logit1, "(M1) Probit" =  probit1, "(M2) logit" = logit2,"(M2) Probit" = probit2, "(M3) logit" = logit3,"(M3) Probit" = probit3),
         fmt="%.3f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC',
         stars=c('*' = .05, '**' = .01),
         coef_rename = cm, 
         title = "Logit, Probit with Pseudo R2"
)

summary1
```


